SAMD21 - Fix error for arm-none-eabi-gcc 5.4.0
Unfortunately this requires a change to the SAMD21 SDK.

The build error was:

Error: In file included from
/home/ccollins/tmp/myproj/repos/mynewt_arduino_zero/hw/mcu/atmel/samd21xx/include/mcu/../../src/sam0/utils/cmsis/samd21/include/samd21.h:72:0,
                 from
/home/ccollins/tmp/myproj/repos/mynewt_arduino_zero/hw/mcu/atmel/samd21xx/include/mcu/cortex_m0.h:20,
                 from
/home/ccollins/tmp/myproj/repos/apache-mynewt-core/kernel/os/include/os/arch/cortex_m0/os/os_arch.h:24,
                 from
/home/ccollins/tmp/myproj/repos/apache-mynewt-core/kernel/os/include/os/os.h:88,
                 from
/home/ccollins/tmp/myproj/repos/apache-mynewt-core/libs/newtmgr/include/newtmgr/newtmgr.h:25,
                 from split_netmgr.c:21:
/home/ccollins/tmp/myproj/repos/mynewt_arduino_zero/hw/mcu/atmel/samd21xx/include/mcu/../../src/sam0/utils/cmsis/samd21/include/samd21g18a.h:229:0:
error: "LITTLE_ENDIAN" redefined [-Werror]
 #define LITTLE_ENDIAN          1
 ^
In file included from /usr/arm-none-eabi/include/sys/types.h:67:0,
                 from
/home/ccollins/tmp/myproj/repos/apache-mynewt-core/encoding/json/include/json/json.h:27,
                 from split_netmgr.c:20:
/usr/arm-none-eabi/include/machine/endian.h:17:0: note: this is the
location of the previous definition
 #define LITTLE_ENDIAN _LITTLE_ENDIAN
 ^
cc1: all warnings being treated as errors